/* Auto-generated by scripts/embed-artwork.ps1. */

#ifndef ARROW_ARTWORK_HPP_INCLUDED
#define ARROW_ARTWORK_HPP_INCLUDED

namespace ArrowArtwork
{
    extern const char* arrowData;
    const unsigned int arrowDataSize = 4571136;
    const unsigned int arrowWidth = 192;
    const unsigned int arrowHeight = 5952;
}

#endif // ARROW_ARTWORK_HPP_INCLUDED
