/* Auto-generated by scripts/embed-artwork.ps1. */

#ifndef BACKGROUND_ARTWORK_HPP_INCLUDED
#define BACKGROUND_ARTWORK_HPP_INCLUDED

namespace BackgroundArtwork
{
    extern const char* bgData;
    const unsigned int bgDataSize = 1228800;
    const unsigned int bgWidth = 480;
    const unsigned int bgHeight = 640;
}

#endif // BACKGROUND_ARTWORK_HPP_INCLUDED
